config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy show]

  resources :users, only: %i[new create edit update show]

  resources :questions do
    resources :answers, except: %i[new show]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end  

  get '/users', to: 'users#new' # добавил от себя, так как при перезагрузке страницы на new выдает ошибку пути

  # get '/questions', to: 'questions#index'
  # get '/questions/new', to: 'questions#new'
  # get '/questions/:id', to: 'questions#show'
  # get '/questions/:id/edit', to: 'questions#edit'
  # post '/questions', to: 'questions#create'

  root 'pages#index'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show edit update destroy]

  def index
    @pagy, @questions = pagy Question.order(created_at: :desc)
    @questions = @questions.decorate
  end

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy @question.answers.order(created_at: :desc)
    @answers = @answers.decorate
  end

  def new
    @question = Question.new
    # render plain: params
  end

  def edit; end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = 'Question created!'
      redirect_to questions_path
    else
      render :new
    end
  end

  def update
    if @question.update question_params
      flash[:success] = 'Question updated!'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = 'Question deleted!'
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>

<%= form_with model: @question, data: {turbo: false} do |f| %>
  <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
      </div>

      <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
      </div>
  </div>

  <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
      </div>

      <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
      </div>
  </div>

  <%= f.submit "Submit question!", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit Question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Edit Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<%= current_user.inspect %>
<p><%= session.to_h %></p>

<h1 class="mb-4">Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>

<%= pagination @pagy %>

<% @questions.each do |question| %>
  <article class="card mt-3">
    <div class="card-body">
      <h4><%= question.title %></h4>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%= truncate strip_tags(question.body), length: 70 %>
        </p>
      </section>
      
      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger',
        data: {method: :delete, confirm: 'Are you sure?'}  %>
    </div>
  </article>
<% end %>

<%= pagination @pagy %>

app/views/questions/new.html.erb
<% provide :page_title, 'New Question' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">New Question</h1>

<%= render 'form' %>

app/views/questions/q.html.erb
fewffwfewfwefwfdsfsfwef

app/views/questions/show.html.erb
<% provide :page_title, @question.title %>
<% currently_at 'Questions' %>

<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
  <%= @question.formatted_created_at %>
</time>

<p class="lead my-3">
  <%= sanitize @question.body %>
</p>

<div class="btn-group">
  <%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
  <%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
              data: {method: :delete, confirm: 'Are you sure?'}  %>
</div>

<hr class="my-3">

<h2>Write your answer</h2>

<%= render 'answers/form' %>

<h2 class="mt-5">Answers</h2>

<%== pagination @pagy %>

<%= render partial: 'answers/answer', collection: @answers,
  as: :answer, locals: {question: @question} %>

<%= pagination @pagy %>