config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy show]

  resources :users, only: %i[new create edit update show]

  resources :questions do
    resources :answers, except: %i[new show]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end  

  get '/users', to: 'users#new' # добавил от себя, так как при перезагрузке страницы на new выдает ошибку пути

  # get '/questions', to: 'questions#index'
  # get '/questions/new', to: 'questions#new'
  # get '/questions/:id', to: 'questions#show'
  # get '/questions/:id/edit', to: 'questions#edit'
  # post '/questions', to: 'questions#create'

  root 'pages#index'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_question!
  before_action :set_answer!, except: :create

  def edit; end

  def create
    @answer = @question.answers.build answer_params
    if @answer.save
      flash[:success] = 'Answer created!'
      redirect_to question_path(@question)
    else
      @question = @question.decorate
      @pagy, @answers = pagy @question.answers.order(created_at: :desc)
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated!'
      redirect_to question_path(@question, anchor: dom_id(@answer))
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer deleted!'
    redirect_to question_path(@question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end

  def set_answer!
    @answer = @question.answers.find params[:id]
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small><time datetime="<%= answer.formatted_created_at %>">
        <%= answer.formatted_created_at %>
      </time></small>
      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    <%= link_to 'Edit', edit_question_answer_path(question, answer), 
      class: 'btn btn-info btn-sm' %>
    <%= link_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
      data: {method: :delete, confirm: "Are you sure?"} %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer], data: {turbo: false} do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control', required: true %>
    </div>
  </div>
  
  <%= f.submit "Submit answer!", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit Answer' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Edit Answer</h1>

<%= render 'form' %>